greybaron/campus-unbloat

package-lock.json
src/lib/DashboardModal.svelte
src/lib/ExamSignupAccordion.svelte
src/lib/TilesAndModals/CalendarModal.svelte
src/lib/TilesAndModals/ExamSignupModal.svelte
src/lib/TilesAndModals/MensaModal.svelte
src/routes/api/registerexam/+server.js
src/routes/dashboard/+page.server.ts
src/routes/dashboard/+page.svelte
src/routes/logout/+server.ts
tailwind.config.ts

the newest version of campus-api has to be pulled

Improve exam tile; call JWT validation server-side and automatically revive the session if expired

---

package-lock.json
package.json
src/lib/TilesAndModals/DashReorderModal.svelte
src/routes/dashboard/+page.svelte
svelte.config.js

Tim cook would be proud i tell you hwat

Implement Dashboard tile reordering

---

src/routes/dashboard/+page.svelte

bruh moment

---

src/routes/dashboard/+page.svelte

heißfix 69

---

src/lib/DashboardTile.svelte
src/lib/TSHelpers/ComponentOrder.ts
src/lib/TilesAndModals/BasicInfoTile.svelte
src/lib/TilesAndModals/BlockplanTile.svelte
src/lib/types.ts
src/routes/api/timeline/+server.js
src/routes/dashboard/+page.svelte

Because in this world, spiderman, you either bloat or blow 🥶

add blockplan tile

---

src/routes/+layout.svelte

This reverts commit 1852f759fca7a08b4b02e13684043913627b9a1c.

Revert "optimize performance of rechtliches back redirect"

---

src/routes/+page.server.ts

Forward client IP for login attempt rate limiting, improve login error messages

---

src/lib/DashboardTile.svelte
src/lib/TSHelpers/ComponentOrder.ts
src/lib/TilesAndModals/BasicInfoTile.svelte
src/lib/TilesAndModals/ExamSignupTile.svelte
src/lib/TilesAndModals/MensaTile.svelte
src/routes/dashboard/+page.svelte

touched up the basicinfo/examsignup tile, added a header/footer to the dashboardtile component; used that in mensatile

Some tile layout fixes

---

package-lock.json
src/lib/ExamSignupAccordion.svelte
src/lib/Popups/ExamDetailsPopup.svelte
src/lib/Popups/GradeStatColumn.svelte
src/lib/Popups/GradeStatsPopup.svelte
src/lib/TilesAndModals/GradesModal.svelte
src/lib/types.ts
src/routes/api/gradestats/+server.js

This is the last piece of the puzzle.
All CampusDual features have been implemented, (except for the Documents feature, which is practically cancelled)

Implement exam result stats popup

---

src/app.html
src/routes/+layout.svelte

switch to auto dark/light mode

---

src/lib/DashboardTile.svelte
src/lib/TilesAndModals/CalendarModal.svelte
src/lib/TilesAndModals/CalendarTile.svelte

#80 was added
#76 was automatically fixed by the new feature

feat: synching between tile and modal

---

src/lib/ExamSignupAccordion.svelte
src/lib/TilesAndModals/ExamSignupModal.svelte
src/lib/TilesAndModals/ExamSignupTile.svelte
src/routes/dashboard/+page.svelte

replaces stores with exported funcs/svelte events

Exam signup: refactor state sync of reminders/exam options

---

src/lib/Calendar/CalendarFuncs.ts
src/lib/Calendar/CalendarSelector.svelte
src/lib/Calendar/CalendarView.svelte
src/lib/TilesAndModals/CalendarModal.svelte
src/lib/TilesAndModals/CalendarTile.svelte

hopefully fixed #76 (it works for me. skill issue if it doesnt work for u 🚀) 
structured all calendar related components and files as well

fix: selectedDate is now handled properly on modal and tile

---

src/lib/DashboardTile.svelte
src/lib/TilesAndModals/BasicInfoTile.svelte
src/lib/TilesAndModals/GradesTile.svelte
src/routes/dashboard/+page.svelte

Tiles are also slightly more rounded now

Implement "new grades" badge

---

package-lock.json
package.json
src/lib/Grades/ChartLabel.svelte
src/lib/Grades/PieChart.svelte
src/lib/TilesAndModals/GradesTile.svelte

adds animations and hover tooltip

Grades chart: switch to chart.js

---

package-lock.json
src/lib/Calendar/CalendarSelector.svelte
src/lib/TSHelpers/DateHelper.ts
src/lib/TilesAndModals/BasicInfoTile.svelte
src/lib/TilesAndModals/DashReorderModal.svelte
src/routes/dashboard/+page.svelte

also fixes the dateIsToday bug

Dashoard reordering: use two columns on large screens

---

src/routes/+layout.svelte
static/site.webmanifest

idk if it f'd up iOS, but idc tbh lmfao

fix: changed splash screen icon and fixed layout shifting

---

package-lock.json
package.json
src/lib/Mensa/MensaFuncs.ts
src/lib/Mensa/MensaSelector.svelte
src/lib/TilesAndModals/GradesModal.svelte
src/lib/TilesAndModals/MensaModal.svelte
src/lib/TilesAndModals/MensaTile.svelte
src/lib/TilesAndModals/OpenMensaModal.svelte
src/lib/types.ts

it's second class for now but does the job

Implement openmensa integration

---

package-lock.json
package.json
src/lib/TilesAndModals/OpenMensaModal.svelte
src/routes/api/cancelexam/+server.js
src/routes/api/openmensalist/+server.js

A lot of the openmensa canteens provide no data, so a cache of all canteens that have at least one day is built at mensa api startup

Use filtered and cached openmensa list provided by mensa api

---

src/lib/Calendar/CalendarSelector.svelte
src/lib/TSHelpers/DateHelper.ts
src/lib/TilesAndModals/CalendarModal.svelte
src/lib/TilesAndModals/CalendarTile.svelte

fixes odd behavior when going far back/forward in time on mensa/calendar components

fix incorrect date comparisons

---

.gitignore
package-lock.json
package.json
src/lib/ExamSignup/ExamSignupAccordion.svelte
src/routes/+layout.svelte
vite.config.ts

reduces client bundle size (gzipped) roughly from 400 to 300 kb

Use fontawesome-subset to create minimal webfonts on build

---

README.md
docker-compose.yml
package-lock.json
src/hooks.server.ts
src/lib/Mensa/MealGroupContainer.svelte
src/lib/Mensa/MealView.svelte
src/lib/Mensa/MealViewAccordion.svelte
src/lib/Mensa/MensaFuncs.ts
src/lib/Mensa/MensaSelector.svelte
src/lib/TilesAndModals/MensaModal.svelte
src/lib/TilesAndModals/MensaTile.svelte
src/lib/TilesAndModals/OpenMensaModal.svelte
src/lib/types.ts
src/routes/api/mensa/canteens/+server.js
src/routes/api/mensa/canteens/[canteen]/days/[date]/+server.js
src/routes/api/mensa/openmensacanteens/+server.js
src/routes/datenschutz/+page.svelte
src/routes/impressum/+page.svelte

readme/compose have been updated as well

implement new mensa api structure support, refactor some naming
